[project]
name = "circuit-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mrmustard",
]

[tool.uv.sources]
mrmustard = { git = "https://github.com/XanaduAI/MrMustard.git" }
